/*-------------------------------------------------------------------------------

	BARONY / AUTOMATIA
	Authoritative metadata for the legacy Text Source @script language.

	The catalog is intentionally data-only and depends on no engine headers.  The
	shared parser consumes it directly, Zed renders it, and characterization tests
	cross-check each dispatchEvidence fragment against the current C++ dispatcher.

-------------------------------------------------------------------------------*/

#include "text_source_script.hpp"

namespace TextSourceLanguage
{
	const std::vector<ScriptTagDefinition>& nativeScriptTagDefinitions()
	{
		static const std::vector<ScriptTagDefinition> definitions = {
			{
				"@script", "@script", "@script", "Structure", "", false,
				{ ArgumentKind::None, false, "none", "none", "literal marker" },
				{ AttachmentMode::Unsupported, "Text Source sprite", "map-generation setup",
					false, false, false, true, CommandSafety::Directive },
				"Marks sprite 132 as a script; without it the Text Source remains a message source.",
				"Selects the Text Source script lifecycle during map post-processing.",
				"@script", "@script=1",
				"Legacy setup searches for the marker anywhere in the text; authoring it first is the unambiguous form.",
				"src/actgeneral.cpp: TextSourceScript::parseScriptInMapGeneration",
				{ VerificationLevel::DispatchVerified, true,
					"catalog parser test plus map-generation dispatch seam",
					"script.find(\"@script\")" }
			},
			{
				"@triggerif=", "@triggerif=<condition>", "@triggerif=<condition>",
				"Triggers", "", false,
				{ ArgumentKind::TriggerCondition, true, "one", "# inside attached conditions",
					"always; attached#dies; attached#exists; attached#invisible; attached#visible; attached#interacted" },
				{ AttachmentMode::Unsupported, "script attachment set", "script lifecycle",
					false, false, false, true, CommandSafety::Directive },
				"Without this directive, a script uses circuit power.",
				"Selects an automatic trigger condition evaluated by actTextSource().",
				"@triggerif=always", "@triggerif=never",
				"attached#interacted is implemented only for attached bells; the guide still labels it unavailable.",
				"src/actgeneral.cpp: textSourceProcessScriptTag and Entity::actTextSource",
				{ VerificationLevel::DispatchVerified, true,
					"enumerated-value parser test plus setup/trigger dispatch seam",
					"textSourceProcessScriptTag(script, \"@triggerif=\", src)" }
			},
			{
				"@attachto=", "@attachto=<entity-type>", "@attachto=<entity-type>",
				"Attachment / Targeting", "", false,
				{ ArgumentKind::AttachmentTarget, true, "one", "none",
					"players; monsters; items; gold; bell; breakable; collider; or a current monstertypename" },
				{ AttachmentMode::Unsupported, "players, monsters, items, gold, bells, breakables, colliders",
					"entities selected once during map setup", true, true, false, true,
					CommandSafety::Directive },
				"Without @attachrange, selection uses the Text Source tile.",
				"Builds the script's UID attachment set during map post-processing.",
				"@attachto=players", "@attachto=",
				"Specific monster names come from the runtime monstertypename table. Summon traps and teleporters are not accepted targets.",
				"src/actgeneral.cpp: TextSourceScript::parseScriptInMapGeneration",
				{ VerificationLevel::DispatchVerified, true,
					"word-contract parser test plus map-generation attachment seam",
					"textSourceProcessScriptTag(script, \"@attachto=\", src)" }
			},
			{
				"@attachrange=", "@attachrange=<X,Y|X1-X2,Y1-Y2|all>",
				"@attachrange=<X,Y>", "Attachment / Targeting", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -",
					"integer tile coordinates/ranges or all" },
				{ AttachmentMode::Unsupported, "attachment candidates", "current map coordinates",
					true, true, false, true, CommandSafety::Directive },
				"Omitting the tag uses the Text Source tile.",
				"Defines the coordinate range used by @attachto or @reattachto.",
				"@attachrange=1-3,4-6", "@attachrange=1",
				"Coordinates are packed into 8-bit fields by the legacy dispatcher after map bounds clamping.",
				"src/actgeneral.cpp: parseScriptInMapGeneration and handleTextSourceScript",
				{ VerificationLevel::DispatchVerified, true,
					"map-range parser test plus attachment-range dispatch seam",
					"textSourceProcessScriptTag(script, \"@attachrange=\", src)" }
			},
			{
				"@reattachto=", "@reattachto=<entity-type>", "@reattachto=<entity-type>",
				"Attachment / Targeting", "", false,
				{ ArgumentKind::AttachmentTarget, true, "one", "none",
					"same target domain as @attachto" },
				{ AttachmentMode::NotMeaningful, "players, monsters, items, gold, bells, breakables, colliders",
					"replaces the script UID attachment set when executed", true, true, false, true,
					CommandSafety::GameplayMutation },
				"Without @attachrange, the rescan uses the Text Source tile.",
				"Clears and rebuilds attachments at execution time.",
				"@reattachto=players", "@reattachto=",
				"Order matters: later attached operations use the rebuilt set. The tester blocks the live rescan.",
				"src/actgeneral.cpp: TextSourceScript::handleTextSourceScript reattach branch",
				{ VerificationLevel::DispatchVerified, true,
					"parser/order characterization plus active handler branch",
					"(*it).find(\"@reattachto=\")" }
			},
			{
				"@clrplayer", "@clrplayer", "@clrplayer", "Player State", "", false,
				{ ArgumentKind::None, false, "none", "none", "literal command" },
				{ AttachmentMode::Optional, "players", "attached players or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., applies to connected players in the script's current spatial scope.",
				"Clears player equipment, inventory, and statistics without selecting a new class.",
				"@attached.clrplayer", "@clrplayer=1",
				"Destructive. Remote players are updated through the legacy SCRU path; manual multiplayer verification remains required.",
				"src/actgeneral.cpp: handleTextSourceScript @clrplayer branch",
				{ VerificationLevel::DispatchVerified, true, "parser/prefix test plus active handler branch",
					"(*it).find(\"@clrplayer\")" }
			},
			{
				"@class=", "@class=<class-index>", "@class=<class-index>", "Player State", "", false,
				{ ArgumentKind::Integer, true, "one", "none", "CLASS_BARBARIAN <= value < NUMCLASSES" },
				{ AttachmentMode::Optional, "players", "attached players or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Unavailable DLC classes fall back to Barbarian.",
				"Reinitializes the target player's class and class inventory.",
				"@attached.class=0", "@class=barbarian",
				"Class indices are build/content dependent; use the character-select ordering and test the target build.",
				"src/actgeneral.cpp: handleTextSourceScript @class branch",
				{ VerificationLevel::DispatchVerified, true, "integer/prefix test plus active handler branch",
					"(*it).find(\"@class=\")" }
			},
			{
				"@clrstats", "@clrstats", "@clrstats", "Stats", "", false,
				{ ArgumentKind::None, false, "none", "none", "literal command" },
				{ AttachmentMode::Optional, "players and monsters", "attached creatures or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., applies to connected players.",
				"Resets HP, MP, attributes, level, gold, and experience; inventory is retained.",
				"@attached.clrstats", "@clrstats=1",
				"Remote stat synchronization uses the legacy SCRU packet and needs a live multiplayer check.",
				"src/actgeneral.cpp: handleTextSourceScript @clrstats branch",
				{ VerificationLevel::DispatchVerified, true, "parser/prefix test plus active handler branch",
					"(*it).find(\"@clrstats\")" }
			},
			{
				"@hunger=", "@hunger=<integer>", "@hunger=<value>", "Player State", "", false,
				{ ArgumentKind::Integer, true, "one", "none", "integer; runtime clamps only the upper bound to 2000" },
				{ AttachmentMode::Optional, "players only", "attached players or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., applies to connected players.",
				"Sets player hunger.", "@attached.hunger=250", "@hunger=hungry",
				"The guide says attached monsters are accepted, but the current handler explicitly skips non-player entities.",
				"src/actgeneral.cpp: handleTextSourceScript @hunger branch",
				{ VerificationLevel::DispatchVerified, true, "integer/prefix test plus player-only handler branch",
					"(*it).find(\"@hunger=\")" }
			},
			{
				"@nextlevel=", "@nextlevel=<levels-to-skip>", "@nextlevel=<count>", "Level / Map", "", false,
				{ ArgumentKind::Integer, true, "one", "none", "integer" },
				{ AttachmentMode::NotMeaningful, "global level state", "active runtime map transition",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Sets loadnextlevel and skipLevelsOnLoad.",
				"Requests a level transition by the supplied skip count.",
				"@nextlevel=1", "@nextlevel=down",
				"Divergent-player transition scope is not encoded in this legacy command; do not assume per-player travel.",
				"src/actgeneral.cpp: handleTextSourceScript @nextlevel branch",
				{ VerificationLevel::DispatchVerified, true, "integer test plus active transition branch",
					"(*it).find(\"@nextlevel=\")" }
			},
			{
				"@power=", "@power=<map-range>", "@power=<X,Y>", "Map / Mechanisms", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::NotMeaningful, "permanent pressure plates", "source playable floor in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Existing permanent plates are toggled on; missing positions receive invisible permanent plates.",
				"Powers mechanisms through permanent pressure plates in the selected range.",
				"@power=1,1", "@power=1",
				"New plates inherit the Text Source spatial context; broad ranges can create many entities.",
				"src/actgeneral.cpp: handleTextSourceScript @power branch",
				{ VerificationLevel::DispatchVerified, true, "map-range test plus active mechanism branch",
					"(*it).find(\"@power=\")" }
			},
			{
				"@unpower=", "@unpower=<map-range>", "@unpower=<X,Y>", "Map / Mechanisms", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::NotMeaningful, "permanent pressure plates", "source playable floor in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Only existing permanent plates are affected.",
				"Turns off permanent pressure plates in the selected range and disables interaction on those toggled.",
				"@unpower=1,1", "@unpower=1",
				"Temporary pressure plates are not handled.",
				"src/actgeneral.cpp: handleTextSourceScript @unpower branch",
				{ VerificationLevel::DispatchVerified, true, "map-range test plus active mechanism branch",
					"(*it).find(\"@unpower=\")" }
			},
			{
				"@wire=", "@wire=<map-range>", "@wire=<X,Y>", "Map / Mechanisms", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::NotMeaningful, "circuit entities", "source playable floor in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Missing circuit positions receive invisible depowered wires.",
				"Creates circuit entities in the selected range and refreshes neighbors.",
				"@wire=1,1", "@wire=1",
				"Implemented in current code but absent from the official guide. New wires inherit source spatial identity; local z remains the mechanism's fixed value 5.",
				"src/actgeneral.cpp: handleTextSourceScript @wire branch",
				{ VerificationLevel::DispatchVerified, true, "map-range test plus active circuit branch",
					"(*it).find(\"@wire=\")" }
			},
			{
				"@unwire=", "@unwire=<map-range>", "@unwire=<X,Y>", "Map / Mechanisms", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::NotMeaningful, "circuit entities", "source playable floor in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Only existing circuit entities are affected.",
				"Depowers and removes circuit entities in the selected range.",
				"@unwire=1,1", "@unwire=1",
				"Implemented in current code but absent from the official guide; destructive to live mechanism entities.",
				"src/actgeneral.cpp: handleTextSourceScript @unwire branch",
				{ VerificationLevel::DispatchVerified, true, "map-range test plus active circuit branch",
					"(*it).find(\"@unwire=\")" }
			},
			{
				"@freezemonsters=", "@freezemonsters=<map-range>", "@freezemonsters=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "monsters", "attached monsters or source-floor monsters in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans monsters in the selected source-floor range.",
				"Applies the indefinite stunned effect used by the legacy script freeze operation.",
				"@attached.freezemonsters=all", "@freezemonsters=1",
				"This is implemented as EFF_STUNNED with duration -1, not a separate freeze flag.",
				"src/actgeneral.cpp: handleTextSourceScript @freezemonsters branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active monster branch",
					"(*it).find(\"@freezemonsters=\")" }
			},
			{
				"@unfreezemonsters=", "@unfreezemonsters=<map-range>", "@unfreezemonsters=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "monsters", "attached monsters or source-floor monsters in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans monsters in the selected source-floor range.",
				"Clears the stunned effect used by @freezemonsters.",
				"@attached.unfreezemonsters=all", "@unfreezemonsters=1",
				"Clears EFF_STUNNED generally; it does not track whether this script originally applied it.",
				"src/actgeneral.cpp: handleTextSourceScript @unfreezemonsters branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active monster branch",
					"(*it).find(\"@unfreezemonsters=\")" }
			},
			{
				"@seteffect=", "@attached.seteffect=<effect-range;duration-range>",
				"@attached.seteffect=<effect;seconds>", "Effects", "", false,
				{ ArgumentKind::EffectAndDuration, true, "two", "; and -",
					"effect index/range; duration seconds/range" },
				{ AttachmentMode::Required, "attached players or monsters", "attachment identities",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., the current handler performs no mutation.",
				"Applies one or more effects for a packed duration.",
				"@attached.seteffect=5;10", "@attached.seteffect=5",
				"Effect support varies by effect implementation. Random duration uses the legacy exclusive-width expression and needs live verification.",
				"src/actgeneral.cpp: handleTextSourceScript @seteffect branch",
				{ VerificationLevel::DispatchVerified, true, "effect-pair/prefix test plus active effect branch",
					"(*it).find(\"@seteffect=\")" }
			},
			{
				"@clreffect=", "@attached.clreffect=<effect-or-range>",
				"@attached.clreffect=<effect>", "Effects", "", false,
				{ ArgumentKind::EffectRange, true, "one", "- for a range", "effect index or inclusive range" },
				{ AttachmentMode::Required, "attached players or monsters", "attachment identities",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., the current handler performs no mutation.",
				"Clears one or more effects.", "@attached.clreffect=5", "@attached.clreffect=none",
				"Indices outside NUMEFFECTS are ignored by the execution loop after legacy 8-bit packing.",
				"src/actgeneral.cpp: handleTextSourceScript @clreffect branch",
				{ VerificationLevel::DispatchVerified, true, "effect-range/prefix test plus active effect branch",
					"(*it).find(\"@clreffect=\")" }
			},
			{
				"@findtarget=", "@attached.findtarget=<map-range>",
				"@attached.findtarget=<X,Y>", "Attachment / Targeting", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Required, "attached monsters; enemy players or monsters as candidates",
					"source playable floor in the active MapInstance", true, true, false, true,
					CommandSafety::GameplayMutation },
				"Without @attached., the current handler performs no mutation.",
				"Assigns the nearest enemy candidate within range and 256 world units as an attack target.",
				"@attached.findtarget=1-4,1-4", "@attached.findtarget=1",
				"Line-of-sight tracing is commented out. The separate guide keyword @findanytarget is not implemented.",
				"src/actgeneral.cpp: handleTextSourceScript @findtarget branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active targeting branch",
					"(*it).find(\"@findtarget=\")" }
			},
			{
				"@killall=", "@killall=<map-range>", "@killall=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "monsters", "attached monsters or source-floor monsters in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans all monsters in range.",
				"Sets matching monsters' HP to zero, including followers.",
				"@attached.killall=all", "@killall=1",
				"Destructive and not executed by the editor sandbox.",
				"src/actgeneral.cpp: handleTextSourceScript @killall branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active kill branch",
					"(*it).find(\"@killall=\")" }
			},
			{
				"@killenemies=", "@killenemies=<map-range>", "@killenemies=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "monsters", "attached monsters or source-floor monsters in the active MapInstance",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., kills non-followers in range.",
				"Sets selected monsters' HP to zero using the handler's allegiance filter.",
				"@killenemies=1,1", "@killenemies=1",
				"Current attached-path condition selects monsters with a player leader, opposite the nonattached path and guide wording. Treat attached behavior as a known legacy defect.",
				"src/actgeneral.cpp: handleTextSourceScript @killenemies branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active kill branch",
					"(*it).find(\"@killenemies=\")" }
			},
			{
				"@damage=", "@attached.damage=<integer>", "@attached.damage=<amount>", "Entity Manipulation", "", false,
				{ ArgumentKind::Integer, true, "one", "none", "integer damage amount" },
				{ AttachmentMode::Required, "attached monsters, chests, doors, furniture, or damageable colliders",
					"attachment identities", false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., the current handler performs no mutation.",
				"Subtracts health from the supported attached entity type.",
				"@attached.damage=10", "@attached.damage=ten",
				"The guide omits chests, doors, and furniture from its target list; damage does not itself force immediate destruction processing.",
				"src/actgeneral.cpp: handleTextSourceScript @damage branch",
				{ VerificationLevel::DispatchVerified, true, "integer/prefix test plus active damage branch",
					"(*it).find(\"@damage=\")" }
			},
			{
				"@explode=", "@explode=<X,Y;sprite> or @attached.explode=<sprite>",
				"@explode=<X,Y;sprite>", "Entity Manipulation", "", false,
				{ ArgumentKind::Explosion, true, "context-dependent", ", then ;",
					"attached sprite integer, or map X,Y with optional ;sprite" },
				{ AttachmentMode::Optional, "attached entities or one map coordinate",
					"source spatial context or attachment positions", true, false, false, true,
					CommandSafety::GameplayMutation },
				"Sprite 0 selects the default explosion.",
				"Spawns an explosion at each attachment or at the supplied map tile.",
				"@explode=1,1;0", "@explode=1,1;bad",
				"The attached and nonattached value shapes differ. Explosion z is generated by the legacy effect helper.",
				"src/actgeneral.cpp: handleTextSourceScript @explode branch",
				{ VerificationLevel::DispatchVerified, true, "context-value/prefix test plus active explosion branch",
					"(*it).find(\"@explode=\")" }
			},
			{
				"@nodropitems=", "@nodropitems=<map-range>", "@nodropitems=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "monsters", "attached monsters or source-floor non-followers",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans non-follower monsters in range.",
				"Sets monsterNoDropItems on matching monsters.",
				"@attached.nodropitems=all", "@nodropitems=1",
				"The flag affects later death drops and is therefore persistent gameplay state.",
				"src/actgeneral.cpp: handleTextSourceScript @nodropitems branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active monster branch",
					"(*it).find(\"@nodropitems=\")" }
			},
			{
				"@copyNPC=", "@copyNPC=<npc-template-index>", "@copyNPC=<template-index>", "Monster / NPC", "", false,
				{ ArgumentKind::Integer, true, "one", "none", "low 8-bit scriptNPC MISC_FLAGS NPC value" },
				{ AttachmentMode::Optional, "players or monsters; human scriptNPC template",
					"active MapInstance template search and attached/scoped targets", false, false, true, true,
					CommandSafety::GameplayMutation },
				"Without @attached., copies to scoped connected players.",
				"Copies stats, equipment, and inventory from a monster named scriptNPC with the selected NPC flag.",
				"@attached.copyNPC=0", "@copyNPC=template",
				"The guide's $summon/summon-trap variant is not implemented. S.A.M item identity is resolved through current item helpers; there is no stable-ID script literal.",
				"src/actgeneral.cpp: handleTextSourceScript @copyNPC branch",
				{ VerificationLevel::DispatchVerified, true, "integer/prefix test plus active copy branch",
					"(*it).find(\"@copyNPC=\")" }
			},
			{
				"@setenemy=", "@setenemy=<map-range>", "@setenemy=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "non-follower monsters", "attached monsters or source-floor monsters",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans non-follower monsters in range.",
				"Forces matching monsters to player-enemy allegiance.",
				"@attached.setenemy=all", "@setenemy=1",
				"The guide's summon-trap variant is not implemented.",
				"src/actgeneral.cpp: handleTextSourceScript @setenemy branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active faction branch",
					"(*it).find(\"@setenemy=\")" }
			},
			{
				"@setally=", "@setally=<map-range>", "@setally=<X,Y>", "Monster / NPC", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "bounded map tile range or all" },
				{ AttachmentMode::Optional, "non-follower monsters", "attached monsters or source-floor monsters",
					true, true, true, true, CommandSafety::GameplayMutation },
				"Without @attached., scans non-follower monsters in range.",
				"Forces matching monsters to player-ally allegiance.",
				"@attached.setally=all", "@setally=1",
				"Unlike @setenemy, the current branch does not explicitly call serverUpdateEntityStatFlag; live multiplayer verification is required.",
				"src/actgeneral.cpp: handleTextSourceScript @setally branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active faction branch",
					"(*it).find(\"@setally=\")" }
			},
			{
				"@setvar=", "@setvar=<name,integer>", "@setvar=<name,value>", "Variables", "", false,
				{ ArgumentKind::SetVariable, true, "two", ",", "non-empty name and integer value" },
				{ AttachmentMode::NotMeaningful, "process script-variable map", "runtime session",
					false, false, false, true, CommandSafety::DisposableState },
				"A repeated name replaces its previous integer.",
				"Writes the script variable and notifies the achievement observer in gameplay.",
				"@setvar=door_open,1", "@setvar=door_open",
				"The variable map is not a S.A.M stable-ID registry and is cleared at lifecycle reset points.",
				"src/actgeneral.cpp: textSourceProcessScriptTag and @setvar branch",
				{ VerificationLevel::BehaviorVerified, false,
					"shared argument decoder plus disposable TestSession state-transition test and runtime dispatch seam",
					"(*it).find(\"@setvar=\")" }
			},
			{
				"@addtomonsters=", "@attached.addtomonsters=<map-range>",
				"@attached.addtomonsters=<X,Y>", "Inventory / Items", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "monster destination tile range" },
				{ AttachmentMode::Required, "attached world items; monster destinations",
					"source playable floor in the active MapInstance", true, true, true, true,
					CommandSafety::GameplayMutation },
				"Requires @attachto=items; otherwise the handler is a no-op.",
				"Copies each attached item stack into every monster inventory in range, then removes the world item.",
				"@attached.addtomonsters=1,1", "@attached.addtomonsters=1",
				"Current item helpers reject unavailable numeric-only S.A.M custom IDs. The world entity is now retained unless at least one monster transfer succeeds; missing-mod records are not substituted.",
				"src/actgeneral.cpp: handleTextSourceScript @addtomonsters branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active inventory branch",
					"(*it).find(\"@addtomonsters=\")" }
			},
			{
				"@equipitems=", "@attached.equipitems=<map-range>",
				"@attached.equipitems=<X,Y>", "Inventory / Items", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "world-item source tile range" },
				{ AttachmentMode::Required, "attached monsters; world items",
					"source playable floor in the active MapInstance", true, true, true, true,
					CommandSafety::GameplayMutation },
				"Requires attached monsters; otherwise the handler is a no-op.",
				"Copies matching world items into compatible equipment slots, then removes those world entities.",
				"@attached.equipitems=1,1", "@attached.equipitems=1",
				"Existing equipment is overwritten. Items remain in the world when no compatible target slot/monster succeeds; custom S.A.M slot metadata must be installed in the current runtime registry.",
				"src/actgeneral.cpp: handleTextSourceScript @equipitems branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active equipment branch",
					"(*it).find(\"@equipitems=\")" }
			},
			{
				"@pickupitems=", "@attached.pickupitems=<map-range>",
				"@attached.pickupitems=<X,Y>", "Inventory / Items", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "world-item source tile range" },
				{ AttachmentMode::Required, "attached players or monsters; world items",
					"source playable floor in the active MapInstance", true, true, true, true,
					CommandSafety::GameplayMutation },
				"Requires a player/monster attachment type; otherwise the handler is a no-op.",
				"Copies matching world items into each attached inventory, then removes the world entities.",
				"@attached.pickupitems=1,1", "@attached.pickupitems=1",
				"The same quantity is copied to every target. The world entity is retained when no pickup succeeds; remote-player and S.A.M custom-item flows require live verification.",
				"src/actgeneral.cpp: handleTextSourceScript @pickupitems branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active pickup branch",
					"(*it).find(\"@pickupitems=\")" }
			},
			{
				"@addtochest=", "@attached.addtochest=<map-range>",
				"@attached.addtochest=<X,Y>", "Inventory / Items", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "chest destination tile range" },
				{ AttachmentMode::Required, "attached world items; chest destination",
					"source playable floor in the active MapInstance", true, true, true, true,
					CommandSafety::GameplayMutation },
				"Requires @attachto=items; otherwise the handler is a no-op.",
				"Moves attached world items into the last matching chest in range.",
				"@attached.addtochest=1,1", "@attached.addtochest=1",
				"No matching chest or failed item conversion leaves the world entity untouched. S.A.M runtime IDs are accepted only when the stable registry resolves them.",
				"src/actgeneral.cpp: handleTextSourceScript @addtochest branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active chest branch",
					"(*it).find(\"@addtochest=\")" }
			},
			{
				"@addtobreakable=", "@attached.addtobreakable=<map-range>",
				"@attached.addtobreakable=<X,Y>", "Inventory / Items", "", false,
				{ ArgumentKind::MapRange, true, "two axes or all", ", and -", "breakable destination tile range" },
				{ AttachmentMode::Required, "attached world items or gold; breakable container",
					"source playable floor in the active MapInstance", true, true, true, true,
					CommandSafety::GameplayMutation },
				"Requires an item or gold attachment type; otherwise the handler is a no-op.",
				"Hides attached objects and links them to the last matching breakable container.",
				"@attached.addtobreakable=1,1", "@attached.addtobreakable=1",
				"Only one item is linked; multiple gold entities can be marked, while colliderContainedEntity stores the last UID.",
				"src/actgeneral.cpp: handleTextSourceScript @addtobreakable branch",
				{ VerificationLevel::DispatchVerified, true, "range/prefix test plus active breakable branch",
					"(*it).find(\"@addtobreakable=\")" }
			},
			{
				"@breakablespawn=", "@attached.breakablespawn=<monster-name>",
				"@attached.breakablespawn=<monster-name>", "Monster / NPC", "", false,
				{ ArgumentKind::MonsterName, true, "one", "none", "current monstertypename" },
				{ AttachmentMode::Required, "attached breakable containers", "attachment identities",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Requires @attachto=breakable and an empty colliderHideMonster slot.",
				"Configures the monster type revealed when an attached breakable is destroyed.",
				"@attached.breakablespawn=rat", "@attached.breakablespawn=",
				"The shared parser can establish the word shape; current runtime monstertypename resolution is dispatch-verified and still needs a live fixture.",
				"src/actgeneral.cpp: handleTextSourceScript @breakablespawn branch",
				{ VerificationLevel::DispatchVerified, true, "word/prefix test plus active breakable-spawn branch",
					"(*it).find(\"@breakablespawn=\")" }
			},
			{
				"@breakablejumpspawn=", "@attached.breakablejumpspawn=<monster-name>",
				"@attached.breakablejumpspawn=<monster-name>", "Monster / NPC", "", false,
				{ ArgumentKind::MonsterName, true, "one", "none", "current monstertypename" },
				{ AttachmentMode::Required, "attached breakable containers", "attachment identities",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Requires @attachto=breakable and an empty colliderHideMonster slot.",
				"Configures a proximity jump-spawn by storing 1000 plus the monster type.",
				"@attached.breakablejumpspawn=rat", "@attached.breakablejumpspawn=",
				"The actual proximity/destruction behavior lives in the breakable runtime and needs a live fixture.",
				"src/actgeneral.cpp: handleTextSourceScript @breakablejumpspawn branch",
				{ VerificationLevel::DispatchVerified, true, "word/prefix test plus active breakable-spawn branch",
					"(*it).find(\"@breakablejumpspawn=\")" }
			},
			{
				"@st<STAT>{=|+}", "@st<STR|DEX|CON|INT|PER|CHR><=|+><integer>",
				"@st<STAT>=<value>", "Stats", "", true,
				{ ArgumentKind::StatPattern, true, "one", "= sets; + adds", "six named attributes and integer value" },
				{ AttachmentMode::Optional, "players or monsters", "attached creatures or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., applies to connected players.",
				"Sets or adds to one primary attribute using a generated command family.",
				"@attached.stSTR+1", "@stLCK=1",
				"Current dispatch maps spelling @stINT to CON and @stCON to INT. This compatibility-sensitive defect is documented rather than silently rewritten.",
				"src/actgeneral.cpp: generated NUMSTATS loops in handleTextSourceScript",
				{ VerificationLevel::DispatchVerified, true, "all 12 concrete spellings parser-tested plus generated-loop seam",
					"for ( int i = 0; i < NUMSTATS; ++i )" }
			},
			{
				"@pro<INDEX>{=|+}", "@pro<0..15><=|+><integer>",
				"@pro<index>=<value>", "Proficiencies", "", true,
				{ ArgumentKind::ProficiencyPattern, true, "one", "= or +", "index 0 through 15 and integer value" },
				{ AttachmentMode::Optional, "players or monsters", "attached creatures or scoped connected players",
					false, false, true, true, CommandSafety::GameplayMutation },
				"Without @attached., applies to connected players.",
				"Updates one proficiency using a generated 16-index command family.",
				"@attached.pro0=10", "@pro16=1",
				"Both current '=' and '+' branches call setProficiency; '+' does not add despite the guide wording.",
				"src/actgeneral.cpp: generated NUMPROFICIENCIES loops in handleTextSourceScript",
				{ VerificationLevel::DispatchVerified, true, "all 32 concrete spellings parser-tested plus generated-loop seam",
					"for ( int i = 0; i < NUMPROFICIENCIES; ++i )" }
			}
		};
		return definitions;
	}

	const std::vector<ScriptRecipeDefinition>& scriptRecipeDefinitions()
	{
		static const std::vector<ScriptRecipeDefinition> recipes = {
			{
				"Immediate tile power", "Map / Mechanisms",
				"@script @triggerif=always @power=1,1",
				"Marks a script, triggers it after map startup, and powers tile 1,1.",
				"Dispatch verified only; change the placeholder coordinate before use.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser test and component dispatch cross-check"
			},
			{
				"Attach to players", "Attachment / Targeting",
				"@script @attachto=players @attachrange=all @triggerif=always @attached.hunger=250",
				"Attaches once to players in the current script scope and sets their hunger when the script fires.",
				"The non-destructive parser/dispatch path is tested; live player mutation remains manual.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser/prefix test and component dispatch cross-check"
			},
			{
				"Freeze monsters in a room", "Monster / NPC",
				"@script @attachto=monsters @attachrange=1-3,1-3 @triggerif=always @attached.freezemonsters=all",
				"Attaches to monsters in a small rectangle and applies the legacy indefinite stun.",
				"Replace the coordinates; live effect behavior remains a manual fixture.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser/prefix test and component dispatch cross-check"
			},
			{
				"Item removal opens a tile", "Triggers",
				"@script @attachto=items @attachrange=2,2 @triggerif=attached#dies @power=3,3",
				"Powers tile 3,3 once the originally attached item no longer resolves.",
				"Replace both coordinates; delayed/run-once behavior is controlled by Text Source properties.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser test and setup/execution dispatch cross-check"
			},
			{
				"Set player strength", "Stats",
				"@script @attachto=players @attachrange=all @triggerif=always @attached.stSTR=5",
				"Sets STR to 5 for players selected by the script.",
				"STR has the expected current spelling; CON/INT have the documented legacy swap.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser test and generated stat dispatch cross-check"
			},
			{
				"Apply invisibility", "Effects",
				"@script @attachto=monsters @attachrange=4,4 @triggerif=always @attached.seteffect=5;10",
				"Applies effect index 5 for 10 seconds to attached monsters.",
				"Effect semantics and networking require a live fixture.",
				VerificationLevel::DispatchVerified, true,
				"combined-script parser/prefix test and effect dispatch cross-check"
			}
		};
		return recipes;
	}
}
